### ISSUE TITLE
Brak wskazania nazw ulic w niektórych komunikatach

### ISSUE THREAD

**Issue by polish96** [Zaczero/osm-addr-bot#10]
- https://www.openstreetmap.org/changeset/145716234 (komunikat poprawny)

- https://www.openstreetmap.org/changeset/145725907 (brak wskazania których ulic dotyczy problem)

Według mnie konieczne jest ujednolicenie komunikatów, tak aby za każdym razem lista linków z problemami była poprzedzona przez nazwę ulicy oraz dwukropek. Można ewentualnie zrobić wyjątek gdy problem dotyczy tylko jednej ulicy.

**Comment by Zaczero** [comment]
Jest to wynikiem tego, że grupowanie działa jedynie wtedy kiedy są co najmniej 4 obiekty. Oryginalny zamysł był taki, że jeśli obiektów jest mało, lepiej wysłać krótszą wiadomość (większa szansa na jej przeczytanie), gdyż ręczne otworzenie tych obiektów nie zabierze dużo czasu. Może zmniejszyć limit do 3, zamiast 4 obiektów?

https://github.com/Zaczero/osm-addr-bot/blob/db2942b759b02e8a38c6b6aa5bb681ae626c85d5/check.py#L24

**Comment by polish96** [comment]
> Może zmniejszyć limit do 3, zamiast 4 obiektów?

Myślę, że to dobry pomysł.

**Comment by Zaczero** [comment]
Zaktualizowane
