### ISSUE TITLE
Niepoprawna nazwa ulicy a słowo `ul.` lub `ulica`.

### ISSUE THREAD

**Issue by docentYT** [Zaczero/osm-addr-bot#5]
Dobrym pomysłem mogłoby być, przed sprawdzaniem czy dodana w adresie ulica znajduje się w pobliżu, sprawdzenie czy w nazwie nie znajduje się skrót `ul.` lub słowo `ulica`. Myślę, że jeśli ktoś nowy doda adres z nazwą ulicy: `ul. Ogórkowa` to może nie zrozumieć, że nie powinno być `ul.` w nazwie.

**Comment by kubahaha** [comment]
Dodałem sprawdzanie w PR #14

**Comment by Zaczero** [comment]
Rozwiązane
